# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_install_hook_types: [pre-commit, pre-push, commit-msg]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/PyCQA/bandit
    rev: 1.9.4
    hooks:
      - id: bandit
        args: ["-c", "pyproject.toml"]
        additional_dependencies: ["bandit[toml]"]

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.21.2
    hooks:
      - id: pyupgrade
        args: ["--py313-plus"]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.15.10
    hooks:
      # Run the linter.
      - id: ruff-check
      # Run the formatter.
      - id: ruff-format

  - repo: https://github.com/commitizen-tools/commitizen
    hooks:
      - id: commitizen
      - id: commitizen-branch
        stages:
          - pre-push
    rev: v4.13.9

  - repo: https://github.com/facebook/pyrefly-pre-commit
    rev: 0.60.1
    hooks:
      - id: pyrefly-check
        name: Pyrefly (type checking)
        pass_filenames: false  # Recommended to do full repo checks. However, you can change this to `true` to only check changed files
        language: system  # Use system-installed pyrefly
