language: node_js
node_js:
- lts/*
branches:
  only:
  - master
  - test
env:
  secure: pAKue+LnIL1aIM/020atv5TVFDmIpZLjwbwR7MoKIF2po5Y/FZeVlqELYA0PUwHVTDQiLnENjzsFk/j18HR64Gi/UBa7K8w+XgQgAEkcQ5aqnF8mCp9NByWw6d+U+wh0PNQPZPNRhs2YoEjaa1o9GgAHV21vrjNtdE04jU+I7DPZ/keGL7qJXxZt/R1hwMe0Od9Mm6v4zUXOzQhNIjedCFHJ0YsLj0dsj4MEYRUiYXwU8jvA4dL9ye2M2cahiq+dCrHYH89RD3SUJw5QEChyoCWu7bWnbByXO7/y7tan20JpwA/U4uMAO7l0qJgUiITsaWSJCMG1idjUVnbo7Pq7cDztho/XvqusqrP7fpc7lWm8ZnyESv7Gp9zw3RyYJvTQ2YAx9WN6dJTLjB91RSdyy6/0gxbqr4G9DNcksFOYMsLz8iTaRzv8tXPf/IWzZCuEndIOUbmXxOnbeE55qcllBUvVYyBrmc5Rhfn4lku7qU5m4Oe8Ly+6Y5gFZMxOVU3bShi267QsNIGjVfe6YgTR9QyAv1fvAJQAw9x3ppBdVHvnOXp8AA/v1/Fa/XLa9oVoTreieXxWnHKXwj+bc9/rpYN71i9QpSPQnoIwPBsROmCa97A1bg5e7TabXM2z01sO+vXSCU5dBkLcP644ulmj8QLITIIVi8cLks+P33+Khmk= PORT=3000k
