language: node_js
node_js:
- lts/*
branches:
  only:
  - master
  - test
env:
  secure: VpmKLzdXouP7i4LZn29vEcNbCBnp6ZOsmj6qvtgYa5e5MwLbgoevKfe2jaz5X57winX0A72a4eNGYOT4zbh74SlT9KBaicJwiwil0GMqB6qk2KKL3Quk1OumIYZ8VPiBCVrz2kHSjajwTSsGGwb86o537gEBeHYVOmjUaBLOEcSgYqD3ggJmxZz0T6i6J+41L89EmPyTHNd7bVpmkKOdeyl+YTUrmL52h+tdBBxhctkcxAU8GuFxI26+41fNuSCziHYQQIZDzEsEnT7/GvncCObEYdT9lCr4OjLLMSLu5riyTPyUOuL5bij4H9IQavnuTQwgkmqanBRJw3TCXPDYxLg93ycVqvBD+kz6IfSjNZBuxjWws6O/SsN7nxmrIICJCjh+qn4VoccrgI8vj6Wd+Ke2c4TzjmpPTBSosP2dLzFc82yuOCtV9cA1YTNXOs6tVyhtxfmG+DjUUkbDtDPBJU8AG7NksyOh46+V5v2uUgQPTjTT17WNjZ6Aq8z7NVJclmfShh9HGgWUzeO0gAo60nmYzdnvMT11WGI+H3O7GW8djgvhdbgqSANfRdtMz65xxfU5xoRHztp6dulCPjLzIAq+jMNaTd9qjmTm/f3ZM0S9WzaN11fZWlejsZoJBOYjP/SYCmZOxcSPB5UOh6bHalaEZi9tdjlZtCbY3pBpNNQ=
