# Generated by Django 4.2.1 on 2023-05-20 11:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="article",
            options={},
        ),
        migrations.AlterModelOptions(
            name="blog",
            options={},
        ),
    ]
