/**
 * @api {get} /v1/articles Get articles
 * @apiName GetArticles
 * @apiGroup Articles
 * @apiVersion 1.0.0
 * @apiDescription Retrieves a list of articles. You can query this endpoint with parameter 'news_site' to return
 * articles provided by a particular news site. This endpoint can also be queried with 'search' to search
 * for articles which match your search parameter.
 *
 * Also supports page, limit, offset and sort options.
 *
 * @apiExample Search for articles
 * https://spaceflightnewsapi.net/api/v1/articles?search=dragon
 *
 * @apiExample Search for articles published by SpaceX
 * https://spaceflightnewsapi.net/api/v1/articles?news_site=spacex
 *
 * @apiParam {String} title Title of the article.
 * @apiParam {String} news_site News site that published the article.
 * @apiParam {String} news_site_long Unformatted name of the news site that published the article.
 * @apiParam {String} url URL of the article.
 * @apiParam {String} featured_image Featured image of the article.
 * @apiParam {Number} id ID from the news site.
 * @apiParam {String} _id ID generated by SNAPI.
 * @apiParam {Number} date_published Date when news site added the article
 * @apiParam {Number} date_added Date when article was added to SNAPI
 * @apiParam {Array} categories Array with categories.
 * @apiParam {Array} tags Array with tags.
 *
 * @apiSuccess {String} title Title of the article.
 * @apiSuccess {String} news_site News site that published the article.
 * @apiSuccess {String} news_site_long Unformatted name of the news site that published the article.
 * @apiSuccess {String} url URL of the article.
 * @apiSuccess {String} featured_image Featured image of the article.
 * @apiSuccess {Number} id ID from the news site.
 * @apiSuccess {String} _id ID generated by SNAPI.
 * @apiSuccess {Number} date_published Date when news site added the article.
 * @apiSuccess {Number} date_added Date when article was added to SNAPI.
 * @apiSuccess {Array} categories Array with categories.
 * @apiSuccess {Array} tags Array with tags.
 *
 * @apiSuccessExample Success-Response:
 * HTTP/1.1 200 OK
 * {
 *   "docs": [
 *     {
 *
 *     }
 *   ],
 *   "totalDocs": 719,
 *   "limit": 10,
 *   "hasPrevPage": false,
 *   "hasNextPage": true,
 *   "page": 1,
 *   "totalPages": 72,
 *   "prevPage": null,
 *   "nextPage": 2
 * }
 *
 *
 * @apiErrorExample Error-Response:
 *     HTTP/1.1 400 Bad request
 *     {
 *       "message": "Uh-oh, something went wrong. Please try again!"
 *     }
 */

/**
 * @api {get} /v1/blogs Get blogs
 * @apiName GetBlogs
 * @apiGroup Blogs
 * @apiVersion 1.0.0
 * @apiDescription Retrieves a list of blogs. You can query this endpoint with parameter 'news_site' to return
 * blogs provided by a particular news site. This endpoint can also be queried with 'search' to search
 * for blogs which match your search parameter.
 *
 * Also supports page, limit, offset and sort options.
 *
 * @apiExample Search for blogs
 * https://spaceflightnewsapi.net/api/v1/blogs?search=bennu
 *
 * @apiExample Search for articles published by SpaceX
 * https://spaceflightnewsapi.net/api/v1/blogs?news_site=planetarysociety
 *
 * @apiParam {String} title Title of the blog.
 * @apiParam {String} news_site News site that published the blog.
 * @apiParam {String} news_site_long Unformatted name of the news site that published the blog.
 * @apiParam {String} url URL of the blog.
 * @apiParam {String} featured_image Featured image of the blog.
 * @apiParam {Number} id ID from the news site.
 * @apiParam {String} _id ID generated by SNAPI.
 * @apiParam {Number} date_published Date when news site added the blog
 * @apiParam {Number} date_added Date when blog was added to SNAPI
 * @apiParam {Array} categories Array with categories.
 * @apiParam {Array} tags Array with tags.
 *
 * @apiSuccess {String} title Title of the blogs.
 * @apiSuccess {String} news_site News site that published the blog.
 * @apiSuccess {String} news_site_long Unformatted name of the news site that published the blog.
 * @apiSuccess {String} url URL of the blog.
 * @apiSuccess {String} featured_image Featured image of the blog.
 * @apiSuccess {Number} id ID from the news site.
 * @apiSuccess {String} _id ID generated by SNAPI.
 * @apiSuccess {Number} date_published Date when news site added the blog.
 * @apiSuccess {Number} date_added Date when blog was added to SNAPI.
 * @apiSuccess {Array} categories Array with categories.
 * @apiSuccess {Array} tags Array with tags.
 *
 * @apiSuccessExample Success-Response:
 * HTTP/1.1 200 OK
 * {
 *   "docs": [
 *     {
 *
 *     }
 *   ],
 *   "totalDocs": 719,
 *   "limit": 10,
 *   "hasPrevPage": false,
 *   "hasNextPage": true,
 *   "page": 1,
 *   "totalPages": 72,
 *   "prevPage": null,
 *   "nextPage": 2
 * }
 *
 *
 * @apiErrorExample Error-Response:
 *     HTTP/1.1 400 Bad request
 *     {
 *       "message": "Uh-oh, something went wrong. Please try again!"
 *     }
 */
