name: 'Build Image'
description: 'Builds, tags and pushes an image to the configured registry'
inputs:
  version:  # id of input
    description: 'Version that will be used to tag the image. Should be the version of the API.'
    required: true
  token:
    description: 'GitHub token to use for the action'
    required: true
runs:
  using: "composite"
  steps:
    - name: Update version in pyproject.toml
      shell: bash
      run: poetry version ${{ inputs.version }}

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: |
          ghcr.io/TheSpaceDevs/spaceflightnewsapi
        tags: ${{ inputs.version }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ inputs.token }}

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v6
      with:
        cache-from: type=gha
        cache-to: type=gha,mode=max
        load: true
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
