# Generated by Django 4.2.9 on 2024-01-25 19:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_article_is_deleted_blog_is_deleted_report_is_deleted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="blog",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="report",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
