# Generated by Django 4.2.16 on 2024-12-21 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_alter_article_updated_at_alter_blog_updated_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Socials",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("x", models.URLField(blank=True)),
                ("youtube", models.URLField(blank=True)),
                ("instagram", models.URLField(blank=True)),
            ],
            options={
                "verbose_name_plural": "Socials",
            },
        ),
        migrations.CreateModel(
            name="Author",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=250)),
                (
                    "socials",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="api.socials"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="article",
            name="authors",
            field=models.ManyToManyField(blank=True, to="api.author"),
        ),
        migrations.AddField(
            model_name="blog",
            name="authors",
            field=models.ManyToManyField(blank=True, to="api.author"),
        ),
        migrations.AddField(
            model_name="report",
            name="authors",
            field=models.ManyToManyField(blank=True, to="api.author"),
        ),
    ]
