# Generated by Django 4.2.16 on 2024-12-16 13:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_alter_article_updated_at_alter_blog_updated_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name="article",
            name="authors",
            field=models.ManyToManyField(blank=True, to="api.author"),
        ),
        migrations.AddField(
            model_name="blog",
            name="authors",
            field=models.ManyToManyField(blank=True, to="api.author"),
        ),
        migrations.AddField(
            model_name="report",
            name="authors",
            field=models.ManyToManyField(blank=True, to="api.author"),
        ),
    ]
