# Generated by Django 5.2.4 on 2025-08-14 14:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_socials_bluesky_socials_linkedin_socials_mastodon_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="audited",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="blog",
            name="audited",
            field=models.BooleanField(default=False),
        ),
    ]
