# Generated by Django 5.2.12 on 2026-04-04 15:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0007_add_audited_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="summary",
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name="article",
            name="title",
            field=models.CharField(db_index=True, max_length=250),
        ),
        migrations.AlterField(
            model_name="author",
            name="name",
            field=models.CharField(db_index=True, max_length=250),
        ),
        migrations.AlterField(
            model_name="blog",
            name="summary",
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name="blog",
            name="title",
            field=models.CharField(db_index=True, max_length=250),
        ),
        migrations.AlterField(
            model_name="newssite",
            name="name",
            field=models.CharField(db_index=True, max_length=250),
        ),
        migrations.AlterField(
            model_name="report",
            name="summary",
            field=models.TextField(blank=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="report",
            name="title",
            field=models.CharField(db_index=True, max_length=250),
        ),
    ]
