name: Run cleanup tasks

on:
  workflow_dispatch:

jobs:
  delete_runs:
    runs-on: ubuntu-latest
    steps:
      - name: Delete workflow runs
        uses: dmvict/clean-workflow-runs@v1.0.0
        with:
          token: ${{ secrets.CR_PAT }}
          save_min_runs_number: 0
