name: Run CodSpeed Benchmarks

on:
  push:
      branches:
        - "main"
  pull_request:
    branches:
      - "main"
  workflow_dispatch:

env:
  SECRET_KEY: "some-insecure-key"
  DATABASE_URL: "postgresql://postgres:postgres@localhost:5432/postgres"
  CSRF_TRUSTED_ORIGIN: http://127.0.0.1
  CELERY_BROKER_URL: "redis://localhost:6379/0"

jobs:
  benchmarks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python and Poetry
        uses: './.github/actions/setup-python'
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: uv sync --frozen

      - name: Run benchmarks
        uses: CodSpeedHQ/action@v3
        with:
          token: ${{ secrets.CODSPEED_TOKEN }}
          run: uv run pytest --codspeed
