name: Run CodSpeed Benchmarks

on:
  pull_request:
    branches:
      - "main" # or "master"
  workflow_dispatch:

env:
  SECRET_KEY: "some-insecure-key"
  DATABASE_URL: "postgresql://postgres:postgres@localhost:5432/postgres"
  CSRF_TRUSTED_ORIGIN: http://127.0.0.1
  CELERY_BROKER_URL: "redis://localhost:6379/0"

jobs:
  benchmarks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python and Poetry
        uses: './.github/actions/setup-python'
        with:
          python-version: "3.12"
          poetry-version: "1.8.0"

      - name: Install dependencies
        run: |
          poetry export -f requirements.txt --output requirements.txt --without-hashes --with=dev
          pip install -r requirements.txt -e .

      - name: Run benchmarks
        uses: CodSpeedHQ/action@v2
        with:
          token: ${{ secrets.CODSPEED_TOKEN }}
          run: pytest --codspeed
