name: Run tests on PR
on:
  pull_request:

jobs:
  run_pre_commit:
    name: Run pre-commit
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Run pre-commit
        run: pre-commit run --all-files
