name: Run Renovate

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

env:
  RENOVATE_TOKEN: ${{secrets.RENOVATE_TOKEN}}
  RENOVATE_REPOSITORIES: "TheSpaceDevs/spaceflightnewsapi"
  RENOVATE_DETECT_HOST_RULES_FROM_ENV: true
  RENOVATE_PYPI_PYPI_THESPACEDEVS_COM_USERNAME: ${{secrets.RENOVATE_PYPI_PYPI_THESPACEDEVS_COM_USERNAME}}
  RENOVATE_PYPI_PYPI_THESPACEDEVS_COM_PASSWORD: ${{secrets.RENOVATE_PYPI_PYPI_THESPACEDEVS_COM_PASSWORD}}

  UV_INDEX_TSD_USERNAME: ${{secrets.UV_INDEX_TSD_USERNAME}}
  UV_INDEX_TSD_PASSWORD: ${{secrets.UV_INDEX_TSD_PASSWORD}}

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Renovate Bot GitHub Action
        uses: renovatebot/github-action@v42.0.3
