name: Run renovate

on:
  workflow_dispatch:
  pull_request: # Temp, to test
  schedule:
    - cron: '0 0 * * *'

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Renovate Bot GitHub Action
        uses: renovatebot/github-action@v42.0.3
