name: Run Renovate

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

env:
  RENOVATE_TOKEN: ${{secrets.RENOVATE_TOKEN}}
  RENOVATE_REPOSITORIES: "TheSpaceDevs/spaceflightnewsapi"
  UV_INDEX_TSD_USERNAME: ${{secrets.UV_INDEX_TSD_USERNAME}}
  UV_INDEX_TSD_PASSWORD: ${{secrets.UV_INDEX_TSD_PASSWORD}}

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Renovate Bot GitHub Action
        uses: renovatebot/github-action@v42.0.3
