name: Release with Python Semantic Release

on:
  workflow_dispatch: {}
  push:
    branches:
      - production
      - staging


jobs:
  release:
    runs-on: ubuntu-latest
    concurrency: release

    env:
        UV_INDEX_TSD_USERNAME: ${{ secrets.UV_INDEX_TSD_USERNAME }}
        UV_INDEX_TSD_PASSWORD: ${{ secrets.UV_INDEX_TSD_PASSWORD }}

    steps:
      - name: Generate a token
        id: generate_token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ secrets.SNAPI_APP_ID }}
          private-key: ${{ secrets.SNAPI_PRIVATE_KEY }}

      - name: Setup | Install uv
        uses: astral-sh/setup-uv@v6

      - name: Setup | Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ steps.generate_token.outputs.token }}
          fetch-depth: 0

      - name: Setup | Install the dependecies and project
        run: |
          uv sync

      - name: Release | Run semantic-release
        env:
          GH_TOKEN: ${{ steps.generate_token.outputs.token }}
        run: |
          uv run semantic-release version
