name: Build and deploy to staging
on:
  release:
    types:
      - prereleased

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Check out the repo
        uses: actions/checkout@v5

      - name: Build Image
        uses: ./.github/actions/build-image
        with:
          version: ${{ github.event.release.tag_name }}
          token: ${{ secrets.GITHUB_TOKEN }}
          repository_username: ${{ secrets.UV_INDEX_TSD_USERNAME }}
          repository_password: ${{ secrets.UV_INDEX_TSD_PASSWORD }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment: TSD Staging

    steps:
      - name: Checkout the deployments repo
        uses: actions/checkout@v5
        with:
          repository: 'TheSpaceDevs/TSD-Deployments'
          path: 'deployments'
          token: ${{ secrets.PAT }}  # https://github.com/actions/checkout?tab=readme-ov-file#checkout-multiple-repos-private

      - name: Helm 3
        uses: WyriHaximus/github-action-helm3@v4.0.2
        with:
          kubeconfig: '${{ secrets.KUBECONFIG }}'
          overrule_existing_kubeconfig: "true"
          exec: helm upgrade snapi-staging -f ./deployments/snapi-django/values.yaml -f ./deployments/snapi-django/values-staging.yaml --set image.tag=${{ github.event.release.tag_name }} ./deployments/snapi-django
