name: Build and deploy to staging
on:
  release:
    types:
      - prereleased

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/spaceflightnewsapi/spaceflightnewsapi
          tags: |
            type=ref,event=tag

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}


  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment: TSD Staging

    steps:
      - name: Checkout the deployments repo
        uses: actions/checkout@v4
        with:
          repository: 'TheSpaceDevs/TSD-Deployments'
          path: 'deployments'
          token: ${{ secrets.GITHUB_TOKEN }}


      - name: Helm 3
        uses: WyriHaximus/github-action-helm3@v4.0.1
        with:
          kubeconfig: '${{ secrets.KUBECONFIG }}'
          overrule_existing_kubeconfig: "true"
          exec: helm upgrade snapi-staging ./deployments/snapi-django --set image.tag=${{ github.event.release.tag_name }}
